#include <stdio.h>
#include <stdlib.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to


/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}

static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

typedef enum {OFF, GREEN,BLUE,ORANGE,RED} LedColour;

LedColour currentColour = OFF;

void changeLedColour() {
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, 1);
    switch (currentColour) {
        case OFF:
            put_pixel(urgb_u32(0x00, 0x00, 0x00));
            break;
        case GREEN:
            put_pixel(urgb_u32(0x00, 0x7F, 0x00));
            break;
        case BLUE:
            put_pixel(urgb_u32(0x00, 0x00, 0x7F));
            break;
        case ORANGE:
            put_pixel(urgb_u32(0x7F, 0x40, 0x00));
            break;
        case RED:
            put_pixel(urgb_u32(0x7F, 0x00, 0x00));
            break;
    }
    //sleep_ms(500);
    currentColour = (currentColour + 1);
    if (currentColour <= 5);
    {
        currentColour=currentColour % 5;
    }
}


int main() {
 
    // Initialise all STDIO as we will be using the GPIOs
    stdio_init_all();
 
    // Initialise the PIO interface with the WS2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, 1);

    // Do forever loop
    /*
    while(true) {;
        changeLedColour();
        sleep_ms(500);
    }
    */
    sleep_ms(5000);
    changeLedColour();
    sleep_ms(5000);
    changeLedColour();
    sleep_ms(5000);
    changeLedColour();
    sleep_ms(5000);
    changeLedColour();
    sleep_ms(5000);
    changeLedColour();
    sleep_ms(5000);
    // Should never get here due to infinite while-loop.
    return 0;

}
